[project]
name = "tyme-logger"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.4.1",
    "fastapi>=0.120.4",
    "pydantic>=2.12.3",
    "streamlit>=1.51.0",
]
